---
Rakefile:
  requires:
    - 'puppet_blacksmith/rake_tasks'
    - 'voxpupuli/release/rake_tasks'
    - 'puppet-strings/tasks'
  changelog_project: 'puppet-metricbeat'

Gemfile:
  optional:
    ':release':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator.git'
        condition: "RUBY_VERSION >= '2.2.2'"
      - gem: 'puppet-blacksmith'
      - gem: 'voxpupuli-release'
        git: 'https://github.com/voxpupuli/voxpupuli-release-gem.git'
      - gem: 'puppet-strings'

appveyor.yml:
  delete: true
